# Generated by Django 3.2 on 2021-05-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0002_auto_20210517_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginmodels',
            old_name='userid',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginmodels',
            old_name='userpassword',
            new_name='username',
        ),
    ]
