# Generated by Django 3.2 on 2021-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0003_auto_20210517_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginmodels',
            options={'managed': False},
        ),
    ]
