# Generated by Django 3.2 on 2021-05-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0004_alter_loginmodels_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginmodels',
            table='test2_loginmodels',
        ),
    ]
