# Generated by Django 3.2 on 2021-05-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0006_loginmodels2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginModels2',
        ),
    ]
